Fixing main.m
trgao10/PuenteAlignment pull request #2
Opened 2018-10-15 17:36 UTC by hkirvesl

This fixes the main.m, which was missing type parameter when calling globalize.

2018-10-15 18:15 UTC, hkirvesl commented
This is the pull-request for enabling the local, sequential run. The gorgon merge is a separate pull-request

2018-10-19 17:46 UTC, JulieWinchester requested changes
Is there a reason why there is a code/main.m file and a separate main.m file? Are they identical? In general, all code files should be in the code directory. 

Also, I'm looking at lines 73 and 130, is there a reason for using a space between function arguments in the first and not in the second? 

Thanks!

2018-11-02 19:15 UTC, JulieWinchester approved these changes

2018-11-02 19:16 UTC, hkirvesl commented
Merging as per discussion on Nov 2 meeting

2018-11-02 19:16 UTC, merged